"""add view counts

Revision ID: 140c932780c2
Revises: dc6e4053bba1
Create Date: 2019-02-27 14:19:18.869328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140c932780c2'
down_revision = 'dc6e4053bba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'view_count')
    op.drop_column('post', 'like_count')
    op.drop_column('post', 'comment_count')
    # ### end Alembic commands ###
