"""created comments table

Revision ID: f4a7674d50e9
Revises: eecd74a0655b
Create Date: 2019-03-05 18:18:42.396339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a7674d50e9'
down_revision = 'eecd74a0655b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'date')
    # ### end Alembic commands ###
